// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: task_exchange.proto

#include "task_exchange.pb.h"
#include "task_exchange.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace pb {

static const char* TaskExchange_method_names[] = {
  "/pb.TaskExchange/RequestForStream",
  "/pb.TaskExchange/RequestForFile",
  "/pb.TaskExchange/RequestForImage",
};

std::unique_ptr< TaskExchange::Stub> TaskExchange::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TaskExchange::Stub> stub(new TaskExchange::Stub(channel, options));
  return stub;
}

TaskExchange::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RequestForStream_(TaskExchange_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_RequestForFile_(TaskExchange_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_RequestForImage_(TaskExchange_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientReader< ::pb::OnAIResultGotReply>* TaskExchange::Stub::RequestForStreamRaw(::grpc::ClientContext* context, const ::pb::StreamTask& request) {
  return ::grpc::internal::ClientReaderFactory< ::pb::OnAIResultGotReply>::Create(channel_.get(), rpcmethod_RequestForStream_, context, request);
}

void TaskExchange::Stub::async::RequestForStream(::grpc::ClientContext* context, const ::pb::StreamTask* request, ::grpc::ClientReadReactor< ::pb::OnAIResultGotReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::pb::OnAIResultGotReply>::Create(stub_->channel_.get(), stub_->rpcmethod_RequestForStream_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::pb::OnAIResultGotReply>* TaskExchange::Stub::AsyncRequestForStreamRaw(::grpc::ClientContext* context, const ::pb::StreamTask& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::pb::OnAIResultGotReply>::Create(channel_.get(), cq, rpcmethod_RequestForStream_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::pb::OnAIResultGotReply>* TaskExchange::Stub::PrepareAsyncRequestForStreamRaw(::grpc::ClientContext* context, const ::pb::StreamTask& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::pb::OnAIResultGotReply>::Create(channel_.get(), cq, rpcmethod_RequestForStream_, context, request, false, nullptr);
}

::grpc::ClientReader< ::pb::OnAIResultGotReply>* TaskExchange::Stub::RequestForFileRaw(::grpc::ClientContext* context, const ::pb::FileTask& request) {
  return ::grpc::internal::ClientReaderFactory< ::pb::OnAIResultGotReply>::Create(channel_.get(), rpcmethod_RequestForFile_, context, request);
}

void TaskExchange::Stub::async::RequestForFile(::grpc::ClientContext* context, const ::pb::FileTask* request, ::grpc::ClientReadReactor< ::pb::OnAIResultGotReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::pb::OnAIResultGotReply>::Create(stub_->channel_.get(), stub_->rpcmethod_RequestForFile_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::pb::OnAIResultGotReply>* TaskExchange::Stub::AsyncRequestForFileRaw(::grpc::ClientContext* context, const ::pb::FileTask& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::pb::OnAIResultGotReply>::Create(channel_.get(), cq, rpcmethod_RequestForFile_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::pb::OnAIResultGotReply>* TaskExchange::Stub::PrepareAsyncRequestForFileRaw(::grpc::ClientContext* context, const ::pb::FileTask& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::pb::OnAIResultGotReply>::Create(channel_.get(), cq, rpcmethod_RequestForFile_, context, request, false, nullptr);
}

::grpc::Status TaskExchange::Stub::RequestForImage(::grpc::ClientContext* context, const ::pb::ImageTask& request, ::pb::OnAIResultGotReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::pb::ImageTask, ::pb::OnAIResultGotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestForImage_, context, request, response);
}

void TaskExchange::Stub::async::RequestForImage(::grpc::ClientContext* context, const ::pb::ImageTask* request, ::pb::OnAIResultGotReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::pb::ImageTask, ::pb::OnAIResultGotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestForImage_, context, request, response, std::move(f));
}

void TaskExchange::Stub::async::RequestForImage(::grpc::ClientContext* context, const ::pb::ImageTask* request, ::pb::OnAIResultGotReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestForImage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pb::OnAIResultGotReply>* TaskExchange::Stub::PrepareAsyncRequestForImageRaw(::grpc::ClientContext* context, const ::pb::ImageTask& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pb::OnAIResultGotReply, ::pb::ImageTask, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestForImage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pb::OnAIResultGotReply>* TaskExchange::Stub::AsyncRequestForImageRaw(::grpc::ClientContext* context, const ::pb::ImageTask& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestForImageRaw(context, request, cq);
  result->StartCall();
  return result;
}

TaskExchange::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TaskExchange_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< TaskExchange::Service, ::pb::StreamTask, ::pb::OnAIResultGotReply>(
          [](TaskExchange::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pb::StreamTask* req,
             ::grpc::ServerWriter<::pb::OnAIResultGotReply>* writer) {
               return service->RequestForStream(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TaskExchange_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< TaskExchange::Service, ::pb::FileTask, ::pb::OnAIResultGotReply>(
          [](TaskExchange::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pb::FileTask* req,
             ::grpc::ServerWriter<::pb::OnAIResultGotReply>* writer) {
               return service->RequestForFile(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TaskExchange_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TaskExchange::Service, ::pb::ImageTask, ::pb::OnAIResultGotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TaskExchange::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pb::ImageTask* req,
             ::pb::OnAIResultGotReply* resp) {
               return service->RequestForImage(ctx, req, resp);
             }, this)));
}

TaskExchange::Service::~Service() {
}

::grpc::Status TaskExchange::Service::RequestForStream(::grpc::ServerContext* context, const ::pb::StreamTask* request, ::grpc::ServerWriter< ::pb::OnAIResultGotReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TaskExchange::Service::RequestForFile(::grpc::ServerContext* context, const ::pb::FileTask* request, ::grpc::ServerWriter< ::pb::OnAIResultGotReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TaskExchange::Service::RequestForImage(::grpc::ServerContext* context, const ::pb::ImageTask* request, ::pb::OnAIResultGotReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace pb

